project_id = "wrvqqvqvwqmfdqvqmaar"

[functions.cancel-subscription]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.email-verification]
verify_jwt = false

[functions.password_token]
verify_jwt = false

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.translator-edge]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.llm-handler-chatgpt]
verify_jwt = false

[functions.llm-handler-gemini]
verify_jwt = false

[functions.chat-send]
verify_jwt = false

[functions.google-whisper]
verify_jwt = false

[functions.google-text-to-speech]
verify_jwt = false

[functions.report-orchestrator]
verify_jwt = false

[functions.get-report-data]
verify_jwt = false

[functions.context-injector]
verify_jwt = false

[functions.keep-warm]
verify_jwt = false

[functions.initiate-auth-report]
verify_jwt = false

[functions.conversation-manager]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.verify-token]
verify_jwt = false

[functions.contact-form-handler]
verify_jwt = false

[functions.create-user-and-verify]
verify_jwt = false

[functions.resend-verification]
verify_jwt = false

[functions.swiss]
verify_jwt = false

[functions.get-prices]
verify_jwt = false

[functions.validate-promo-code]
verify_jwt = false

[functions.verification-emailer]
verify_jwt = false

[functions.google-place-details]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.inboundmessenger]
verify_jwt = false