project_id = "wrvqqvqvwqmfdqvqmaar"

[functions.cancel-subscription]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.email-verification]
verify_jwt = false

[functions.password_token]
verify_jwt = false

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.translator-edge]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false